### PR TITLE
Error page

### PR DESCRIPTION
**Pull request by egueli**
# Description

This PR makes the application show a special web page when the app initialization failed, e.g. because of a camera problem, instead of not having a webapp at all.

## Rationale

When I set up the app for the first time, I could see the ad-hoc access point. I connected to it, then browsed to 192.168.50.1. To my surprise, no page could be loaded. I immediately thought there was a connectivity problem between my browser and the webserver, but found nothing wrong. Only after an investigation involving SSH and `journalctl` I realized that the server didn't start because the camera wasn't found. 
I found this cause-effect relation a bit counter-intuitive, so I thought that the webserver could start anyway, albeit in a lesser form, and inform the user of some failure occurred. This could at least confirm that the problem isn't about network.

## Implementation

This PR wraps the code that sets up the app in a try/except block. If any exception is raised, it starts an "error" Flask app that  shows the exception message.

I noticed that in case of unplugged camera, this message is shown:

> An error occurred: Camera is not enabled. Try running 'sudo raspi-config' and ensure that the camera has been enabled.

It would be nice if the Pi could find out (e.g. via [`vcgencmd`](https://stackoverflow.com/questions/58250817/raspberry-pi-camera-module-check-if-connected#comment102874971_58250817)) if it's a hardware problem or an actual "enable" problem (which shouldn't be the case for pre-made SD images since it's enabled by default), and show the right message. If not possible, the message could be extended to suggest to check the hardware connection as well.

I might do this work in this same PR. I'll publish this as draft for early review, and keep the TODO list updated before merge.

## Type of change

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)
- [ ] This change requires a documentation update

# How Has This Been Tested?

I ran the app on a Pi Zero W with no camera attached, then I browsed to the Pi's IP address. Instead of a "page not found" error, it should show a simple page with an error message.

**Tested on the following devices**:
- [ ] Development environment (Linux, Windows, or MacOS)
- [x] Pi Zero W
- [ ] Pi 3A+
- [x] Pi 3B+
- [ ] Pi 4

# Checklist:

- [x] I have performed a self-review of my own code
- [ ] I have commented my code, particularly in hard-to-understand areas
- [ ] My changes generate no new warnings
- [x] New and existing unit tests pass locally with my changes

# TODO:

- [ ] Make page mobile-friendly
- [x] Suggest to check the camera connection instead of pointing at raspi-config
- [x] Test happy case
- [x] Test on another Pi
- [ ] Check warnings
- [ ] Check unit tests

### CODE REVIEW

**Comment by mikevanis** [comment]
Thanks for your contribution @egueli! It makes a lot of sense to have an error page when the camera is inaccessible / not plugged in correctly. Please give us a little bit of time to review the implementation! 💯

**Comment by egueli** [comment]
Thanks @mikevanis ! I just added the camera-enable-check via `vcgencmd` as described in the PR description. This should make the error message less misleading.
Looking forward for any feedback!

**Comment by yodatak** [comment]
Thanks for this i got the same issue ! when will it be released in img ?

**Comment by mikevanis** [comment]
@yodatak This will be released in v1.6, which is currently cloud building and will be available in a few hours!

**Pull request merged**
